### ISSUE TITLE
Doesn't work inside tables

### ISSUE THREAD

**Issue by franciscolourenco** [popperjs/popper.js#276] opened 2017-05-18 17:10 UTC
### CodePen demo
https://codepen.io/anon/pen/RVeQyL

### Steps to reproduce the problem

1. Put reference element inside of a table
2. Initialize Popper.js on it

### What is the expected behavior?

Popper should show up next to reference element.

### What went wrong?

Popper shows up in wrong location, or if page is scrolled, sometimes it gets hidden.

**Comment by aristidesfl** [comment] 2017-05-19 08:17
EDIT: I've reproduced with popper only and switched the jsbin to codepen.

**Comment by FezVrasta** [comment] 2017-05-19 11:21
Umh that's unexpected 🤔

**Comment by aristidesfl** [comment] 2017-05-19 11:31
Actually the position relative only works here because the table is the size of the element in this case.

**Comment by aristidesfl** [comment] 2017-05-19 12:35
@FezVrasta any idea why this happens?

**Comment by FezVrasta** [comment] 2017-05-19 12:36
Nope, sorry but I'm not at home these days so I'm not able to investigate.

**Comment by aristidesfl** [comment] 2017-06-30 10:22
Updated the codepen to make it more clear

**Comment by mponizil** [comment] 2017-07-20 16:34
I'm seeing the issue as popper.offsetParent returning a grandparent with `position: relative`, instead of the `<td>` container element, and am able to work around it by setting `position: relative` to the `<td>` directly.

**Comment by aristidesfl** [comment] 2017-07-20 16:38
@mponizil that only works partially, because the popper width will be calculated based on the width of the `td`, and so will be constrained if you have a lot of text and want the popper width to adjust automatically.

**Comment by mponizil** [comment] 2017-07-20 16:40
@aristidesfl hah, indeed I realized that just after posting!

**Comment by aristidesfl** [comment] 2017-07-20 16:43
Best workaround I've found so far:
```js
new Tooltip({
      container: document.body,  
      boundariesElement: document.body
})
```

**Comment by FezVrasta** [comment] 2017-07-23 14:32
The problem is this:
![image](https://user-images.githubusercontent.com/5382443/28500212-70d820ba-6fc4-11e7-94b9-89926b5999ed.png)

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent

I guess I'll have to create a custom `offsetParent` implementation to get rid of this quirkiness..

**Comment by FezVrasta** [comment] 2017-07-23 15:01
You all guys, please review #363 and let me know if it fixes your problems.

**Comment by FezVrasta** [comment] 2017-07-26 18:49
released as 1.11.0

**Comment by razzmatazz** [comment] 2018-01-29 15:46
Not sure if it is a big thing to fix, but the fix in #276 doesn't work for `<th>` elements.

**Comment by rufusroflpunch** [comment] 2018-02-23 19:02
I can verify also that this doesn't work in `<th>` elements. I worked around it by changing my `<th>` elements to `<td>` elements, but that does hurt my brain a bit.

**Comment by hally9k** [comment] 2018-04-25 07:04
Agreed, this doesn't work inside `<th>`. Reopen!

**Comment by eliseumds** [comment] 2018-06-01 07:05
I have the same issue. Small tooltips are correctly-positioned, but once they are a bit tall, they get mispositioned. The target is inside a TD.

### Small tooltip (correct)

![screen shot 2018-06-01 at 17 02 20](https://user-images.githubusercontent.com/640840/40826426-e7411244-65bd-11e8-95db-d4b44dcf535b.png)


### Big tooltip (incorrect)

![screen shot 2018-06-01 at 17 02 52](https://user-images.githubusercontent.com/640840/40826434-ec7ed200-65bd-11e8-9eeb-c97811c7289f.png)
![screen shot 2018-06-01 at 17 02 36](https://user-images.githubusercontent.com/640840/40826436-ef4c6e52-65bd-11e8-886d-5586d1ffaca6.png)


### Outside of the table (correct)

![screen shot 2018-06-01 at 17 04 23](https://user-images.githubusercontent.com/640840/40826443-f4d67688-65bd-11e8-8f06-f908d0ab78a2.png)

**Comment by simbunch** [comment] 2018-06-05 18:06
Workaround that works for now:

    <div class="table-responsive" style="margin:-200px 0;">
        <table class="table" style="padding:-200px 0;">
            
        </table>
    </div>

Works if container is outside of `.table-responsive`

**Comment by florianlacreuse** [comment] 2018-08-21 15:58
We still have an issue with popover inside table wrapped in a Bootstrap `table-responsive` container.

* Example KO - table *with* `table-responsive`: https://codepen.io/anon/pen/xabVxp
As you can see, the position of the popover is quite odd / unusual and the popover isn't fully visible.

 * Example OK - table *without* `table-responsive`: https://codepen.io/anon/pen/zJxBBe
Here everything work fine and the popover is fully visible.

I think it may be related to this issue.

**Comment by florianlacreuse** [comment] 2018-10-25 08:08
Update: my issue seems more related to issue #611.

**Comment by FezVrasta** [comment] 2019-12-16 13:38
These issues should be fixed in v2, I don't have any codepen to test it (since the recent examples rely on Bootstrap), but similar table-related issues are fixed so I'm pretty confident.

**Closed** 2019-12-18 19:34 UTC
Labels: # BUG, DIFFICULTY: medium, Fixed in v2, PRIORITY: medium, TARGETS: core

**Comment by memsenpai** [comment] 2021-05-07 09:55
> Best workaround I've found so far:
> 
> ```js
> new Tooltip({
>       container: document.body,  
>       boundariesElement: document.body
> })
> ```

for v1, this is solutions

**Comment by atomiks** [comment] 2022-05-17 12:12
v2 doesn't have any table issues

**Comment by Michael101sh** [comment] 2022-05-17 12:27
Actually, there is, I tried to combine a tooltip in a simple HTML table and it didn't work, but when I changed from <td> to <div> it worked.

**Comment by Michael101sh** [comment] 2022-05-17 14:24
Ok, I found the problem: `overflow: hidden;` (for another purpose).
Thanks @atomiks, your answer made me try again to make it work

**Comment by privatenumber** [comment] 2023-06-03 12:03
This seems to be happening in floating-ui for me.

Wondering if https://github.com/floating-ui/floating-ui/pull/363/ needs to be re-applied? I noticed the unit test is no longer there.

**Comment by Techn1x** [comment] 2023-10-31 07:32
I've also encountered this - I'm running floating-ui/dom 1.3.0 but also tried with 1.5.3 - When I use a `td` it's fine, but if I use a `th` it repeatedly recalculates position
