### ISSUE TITLE
Arrow is positioned incorrectly on first flip update when it has a border

### ISSUE THREAD

**Issue by atomiks** [popperjs/popper.js#784] opened 2019-05-07 14:13 UTC
It's strange because I don't remember seeing this before, but appears in versions from years ago as well. However, I do remember seeing this when the update was only a single one (i.e. programmatic update after a flip), but I thought it was a problem with my own lib and used a double-update hack to work around it. 

Maybe browsers have slowed their resize events down so it's more obvious now? 

### CodePen demo

https://codepen.io/anon/pen/joPVWp

### Steps to reproduce the problem

1.  Resize window **slowly** so popper flips
2.  Watch arrow on very first update - it's offset incorrectly (by half the border width?)
3.  It takes a second update to position it correctly

### What is the expected behavior?

Arrow is positioned correctly on first update

### What went wrong?

Arrow is positioned incorrectly on first update

**Comment by FezVrasta** [comment] 2019-05-07 14:20
I can't reproduce it, or I don't understand what's the issue. May you attach a gif?

**Comment by atomiks** [comment] 2019-05-07 14:22
Hm strange, here you go: https://gyazo.com/cc133950a5fea8ba4af409f7d8a662fb

**Comment by FezVrasta** [comment] 2019-05-07 14:36
Oh, ok I see... Yeah. It needs some investigation.

**Comment by atomiks** [comment] 2019-05-07 15:06
I think I found the issue in `arrow.js`

`getOuterSizes(arrowElement)` returns the `offset{Width,Height}` of the arrow element at the previous update (which previously was the opposite `isVertical`), but the placement has been changed before the new `offset` can be calculated (since the arrow element hasn't updated on the DOM yet)

```js
var isVertical = ['left', 'right'].indexOf(placement) !== -1
var len = isVertical ? 'height' : 'width'
// On the first flip update, this is reading the wrong offset width/height
var arrowElementSize = getOuterSizes(arrowElement)[len]
```

**Comment by atomiks** [comment] 2019-05-07 15:41
Confirmed via this: reads the latest DOM update, rather than latest placement update:

```js
// Previous vertical status on the DOM
var previousIsVertical =
    ['left', 'right'].indexOf(
      arrowElement.parentNode.getAttribute('x-placement'),
    ) !== -1
// Newest vertical status to be updated
var isVertical = ['left', 'right'].indexOf(placement) !== -1

var len = isVertical ? 'height' : 'width'
var arrowLen = previousIsVertical ? 'height' : 'width'
// ...
var arrowElementSize = getOuterSizes(arrowElement)[arrowLen]
```

Not sure how to write the code to fix this (without that terrible hack), hopefully this helps you write the solution though @FezVrasta

**Comment by FezVrasta** [comment] 2019-12-04 18:10
@atomiks is this fixed in v2?

**Comment by atomiks** [comment] 2019-12-05 00:29
Since we're using `getBoundingClientRect` probably but I'll test it to see

**Comment by atomiks** [comment] 2019-12-05 00:31
This is the same problem that this will fix IIRC: https://github.com/popperjs/popper.js/pull/859

**Comment by FezVrasta** [comment] 2019-12-18 19:36
As far I know, this has been fixed in v2 (or at least, it works in the new website)

**Closed** 2019-12-18 19:37 UTC
Labels: # BUG, Fixed in v2, PRIORITY: medium, TARGETS: modifier
