### ISSUE TITLE
Better default for `preventOverflow`

### ISSUE THREAD

**Issue by FezVrasta** [popperjs/popper.js#611] opened 2018-04-11 16:23 UTC
Bootstrap issue: https://github.com/twbs/bootstrap/issues/25428

Basically, we want to have a better way to detect the "scrollParent" so that we don't include elements with `overflow !== initial` that will not actually cut out `position: absolute` elements.

**Comment by FezVrasta** [comment] 2018-07-16 04:23
For anyone that wants to try to implement this, basically there are cases when an element with `overflow` value different from `initial` (e.g. `hidden` or `scroll`) will not prevent its `position: absolute` children elements from overflowing it.

We should first find out when this happens, and then change the `scrollParent` detection algorithm to take in consideration these new finds so that we pick a better parent element.

**Comment by florianlacreuse** [comment] 2018-10-25 08:05
Hi @FezVrasta. I just want to know if there is a chance this will be fixed any time soon? Thanks, keep up the good work!

**Comment by FezVrasta** [comment] 2018-10-25 11:02
No I haven't time to allocate at the moment, but I explained the needed steps [here](https://github.com/FezVrasta/popper.js/issues/611#issuecomment-405146318). A PR would be great.

**Comment by florianlacreuse** [comment] 2018-10-26 15:48
Thanks for the feedback. Unfortunately I don't have the necessary skills in js to push a good PR. We'll use [boundary window](https://popper.js.org/popper-documentation.html#modifiers..preventOverflow.boundariesElement) in the meantime.

**Closed** 2019-12-18 19:34 UTC
Labels: # ENHANCEMENT, DIFFICULTY: medium, Fixed in v2, PRIORITY: medium, TARGETS: modifier

**Comment by realnot** [comment] 2021-04-20 12:18
@florianlacreuse the issue is closed, but this is a problem with latest bootstrap 5 and popper.js. How did you solved?

**Comment by florianlacreuse** [comment] 2021-04-20 12:34
I haven't solved it with BS4 and Popper.js v1 IIRC. This issue is marked as fixed in v2 but I haven't yet had the chance to test the v2.

**Comment by realnot** [comment] 2021-04-20 20:11
> I haven't solved it with BS4 and Popper.js v1 IIRC. This issue is marked as fixed in v2 but I haven't yet had the chance to test the v2.

I just created a fiddle to reproduce the bug. As you can see, filter columns are not visible when you click the dropdown arrow.

[https://jsfiddle.net/0ex91L46/](https://jsfiddle.net/0ex91L46/)

Can we re open this issue or create another one @FezVrasta ?
