### ISSUE TITLE
Tooltip overflowing body

### ISSUE THREAD

**Issue by Simonwep** [popperjs/popper.js#766] opened 2019-04-02 09:36 UTC
### CodePen demo

Sorry, already got this in a JSFiddle:
https://jsfiddle.net/0x7cpavb/

### Steps to reproduce the problem

1.  Put element on the very right of the page
2.  Use element as reference element for tooltip.js

### What is the expected behavior?
Popper prevents this kind of clipping

### What went wrong?
The tooltip gets clipped by the body

### Any other comments?
Used the latest versions via unpkg. Not sure if this really is an issue, but I tried (and searched) in the docs for almost 3 hours and couldn't fix it :suspect: 

Thx for this awesome library :)

**Comment by oliver-dvorski** [comment] 2019-04-08 13:00
That's a bug as far as I can tell.

Tried reproducing it with popper and it would seem that all is fine as long as your tooltip isn't a child of the reference element (https://codesandbox.io/embed/3v35klj546) so maybe you'd want to try using Popper for your tooltip positioning needs?

**Comment by shamel67** [comment] 2019-05-15 21:24
> That's a bug as far as I can tell.
> 
> Tried reproducing it with popper and it would seem that all is fine as long as your tooltip isn't a child of the reference element (https://codesandbox.io/embed/3v35klj546) so maybe you'd want to try using Popper for your tooltip positioning needs?

I tried that sandbox you shared and the popper is cut-off/not positioned correctly. Running Chrome 74.

**Comment by Simonwep** [comment] 2019-05-17 10:58
Since this seams like a bug and is kinda an essential part of popper, could @FezVrasta take a look at it? :suspect:

**Comment by shamel67** [comment] 2019-06-07 14:24
I have a very similar issue - except my tooltip is pretty complex.
I'm attaching an example of a tooltip that works perfectly, and another one overflowing at right.

I tried a bunch of different things without success (specifying CSS dimensions, using boundariesElement, container, etc.).

My code is the simplest it can be - I would expect popper to calculate the tooltip dimension and find the best position automatically:

``
new Tooltip($('#abc143'), {
        html: true,
        title: `<div class="cards_popup_header"><span class="date">${date}</span></div>
                <div class="body"><div class="list_wrapper"><ul class="fa-ul">${listItems}</ul></div></div>`
      });
``

![2019-06-07_10-18-23](https://user-images.githubusercontent.com/4053021/59110768-c7bad080-890d-11e9-87f6-6c73c0e64f77.png)
![2019-06-07_10-18-37](https://user-images.githubusercontent.com/4053021/59110778-cbe6ee00-890d-11e9-9d6d-30285eafec99.png)

**Comment by smth** [comment] 2019-06-30 13:25
Anyone know if there is a version without this bug?

**Comment by atomiks** [comment] 2019-06-30 13:34
It's because the arrow has no size. Give it `width: 1px` and problem is gone

https://jsfiddle.net/3jafz07e/

**Comment by smth** [comment] 2019-06-30 14:01
That doesn't seem to fix the [original jsfiddle](https://jsfiddle.net/0x7cpavb/) @atomiks (nor my local version). Is this issue specific to tooltip.js? I'm using popper.js, and not aware of `.tooltip-arrow` existing.

**Comment by atomiks** [comment] 2019-06-30 14:05
Remove the `boundariesElement` / `container` options and it is fixed in that version as well.

**Comment by Simonwep** [comment] 2019-07-02 05:52
@atomiks Using `document.body` cuts of the tooltip completely: https://jsfiddle.net/9nL3hje0/ (Even stranger it behaves differently than using a string which should be the same). And according to the [tooltip.js](https://popper.js.org/tooltip-documentation.html#new_Tooltip_new) doc it's also possible to use a String e.g. Query Selector.

**Comment by atomiks** [comment] 2019-07-02 06:05
You didn't add the `.tooltip-arrow` CSS width. It's fixed w/ that

**Comment by Simonwep** [comment] 2019-07-02 06:09
This seems more like a hack and not an expected user experience when using this. Shouldn't this be optional? :suspect:

**Comment by atomiks** [comment] 2019-07-02 06:15
I think it's because the default tooltip template includes the arrow. And Popper's calculations require the arrow to have width if it exists as a child with the modifier enabled.

I think I'm wrong on the querySelector thing looking at the source so that's weird.

tbh, maybe @FezVrasta can deprecate Tooltip.js and recommend Tippy.js instead? Especially v5 coming which will be much closer in total bundle size. The most important part of this package is the positioning engine itself so maybe he can purely focus on that instead of Tooltip.js in the future. And no need for the monorepo setup.

**Comment by FezVrasta** [comment] 2019-07-02 08:42
@atomiks yes that's a good plan, Tooltip.js was meant as a way to show how to implement Popper.js into your own libraries, but I see a lot of people want to use it as-is.

**Comment by Wyzix33** [comment] 2019-07-13 20:17
Tooltip.js is perfect for simple projects and way more easy to debug than Tippy.js

**Comment by atomiks** [comment] 2019-07-14 06:04
@Wyzix33 may you make an issue on tippy repo about the debugging difficulties? What makes it harder? Would be helpful to understand in case it requires a large API change before v5 comes out

**Comment by FezVrasta** [comment] 2019-11-22 10:39
Hi, I'm interrupting the development of the `tooltip.js` library to focus on the development of `@popperjs/core` (Popper.js v2).

Please consider switching to [Tippy.js](https://github.com/atomiks/tippyjs), which is a way better alternative to Tooltip.js and is well maintained. Tippy.js still uses Popper.js under the hood, so you will find all your favourite features.

I'll close this issue.

**Closed by FezVrasta** 2019-11-22 10:39 UTC
