### ISSUE TITLE
Inaccurate position inside flex layout

### ISSUE THREAD

**Issue by smth** [popperjs/popper.js#797] opened 2019-07-01 10:03 UTC
I've been getting a few instances where popper element is positioned partially outside the viewport. One common factor has been `display: flex`. I've been able to reproduce this by putting the popper elements inside a nested flex layout (see [codepen](https://codepen.io/anon/pen/JQLjdP)).

### CodePen demo

https://codepen.io/anon/pen/JQLjdP

### Steps to reproduce the problem

1.  Put popper elements inside an element with `display: flex`
2.  Put that element inside another element with `display: flex`
3.  Give the outer wrapper `justify-content: flex-end` to push everything to the right of the screen

### What is the expected behavior?

The popper element to be positioned so that no horizontal scroll is needed.

### What went wrong?

The popper element was positioned partially outside the viewport, requiring a horizontal scroll.

### Any other comments?

Edit: the inner `flex` might not be necessary.

**Comment by FezVrasta** [comment] 2019-07-01 10:35
Could this be a dupe of https://github.com/FezVrasta/popper.js/issues/455?

**Comment by smth** [comment] 2019-07-01 10:50
Doesn't look like it to me. Giving the containers in my example (even) height values doesn't make any difference.

**Comment by namjul** [comment] 2019-11-13 15:40
If you add `left: 0;` to `#pop` it works.

**Comment by FezVrasta** [comment] 2019-12-17 12:11
As pointed out, you need to set some initial CSS to the popper element to make sure it doesn't mess the layout _before_ Popper has a chance to run its logic.

The example works correctly on v2
https://codepen.io/FezVrasta/pen/OJPbrJX

**Closed** 2019-12-18 19:34 UTC
Labels: # BUG, Fixed in v2

**Comment by designbyadrian** [comment] 2020-02-26 13:25
@smth Did you manage to solve this in version 1.X?

**Comment by FezVrasta** [comment] 2020-02-26 13:34
No, the fix landed in v2

**Comment by designbyadrian** [comment] 2020-02-26 13:41
@FezVrasta Thank you, I understand, but you mentioned some initial CSS. I've been struggling for a while, so I wondered if @smth has an example that works.

Unfortunately, I'm locked tor react-popper that hasn't updated to version 2 yet.

**Comment by FezVrasta** [comment] 2020-02-26 13:46
I was referring to https://github.com/popperjs/popper-core/issues/797#issuecomment-553458986

**Comment by the94air** [comment] 2020-02-27 16:29
I had the same issue. My tooltip was inside of a flex element with justify-content between. the button was smaller than my tooltip and I had to retrigger the translate update using `popperTooltip.update()` after the toggle event. Putting it here if someone has the same issue.
https://popper.js.org/docs/v2/migration-guide/#8-update-method-names`

**Comment by benlind** [comment] 2020-07-09 15:42
I fixed this by passing `positionFixed: true` to the [popper options](https://popper.js.org/docs/v1/#defaultspositionfixed).
