### ISSUE TITLE
Incorrect placement of popper if ref is in flex container with odd-numbered height

### ISSUE THREAD

**Issue by haakemon** [popperjs/popper.js#455] opened 2017-10-13 10:54 UTC
### CodePen demo

https://codepen.io/hbogs/pen/XePdRj

### Steps to reproduce the problem

1. Add a container element around the ref, with the following:
* display: flex;
* align-items: center;
* height: 121px; (or any odd-number)
2. The popper will now overlap the ref

Removing the flex, or setting the height to an even number will fix the issue.

### What is the expected behavior?

The popper should not overlap the ref element. 
(The border on the ref element in the codepen example is not needed, but it makes it a lot easier to visualize the problem.)

### What went wrong?

The popper overlaps the ref element with 1px.

### Any other comments?

I might have missed something here, but I dont understand why the size of the ref's container should affect the position of the popper?

**Comment by FezVrasta** [comment] 2017-10-27 09:39
The position of the popper is directly dependent by the position and size of the reference element. To obtain the popper position we do `reference.top + reference.height` or `reference.getBoundingClientRect().bottom`

Looks like flex elements have some quirk that makes the box sizes be wrong in this case. I'm investigating it.

**Comment by ConneXNL** [comment] 2017-11-30 19:47
Also ran into this issue.

**Comment by kjdion84** [comment] 2018-01-01 21:29
Yep this issue goes along with the other positioning issues related to scrollbar.

It seems to me that popper should do its calculations after everything in the dom has loaded, so that it works seamlessly with dynamic elements as well. 

This is the largest issue with the package right now.

**Comment by yuanfux** [comment] 2018-01-20 09:00
need immediate fix

**Comment by TrueRushHunt3r** [comment] 2019-03-15 10:52
@kjdion84 Do you know if the Issue with the scrollbar is still active? Because I am experiencing this behaviour, that my tooltips from Mui only are in the right place (bottom-center) when a scrollbar shows up. When no scrollbar is there, they are shifted by a few (maybe 20px) to the left. But this behaviour started at first when I started to make the root div 100% height.

**Comment by kjjdion** [comment] 2019-03-15 10:56
The issue is that popper does the calculations before the DOM is done loading, and does not factor in new DOM elements added via AJAX etc.

**Comment by TrueRushHunt3r** [comment] 2019-03-15 11:01
mhm... ok. I am now doing a workaround that i am always showing th scrollbar. Not the best solution but IMO better then misspositioned tooltips '^^

**Comment by kjjdion** [comment] 2019-03-15 11:05
The solution is to use html `title` attribute instead.

**Comment by TrueRushHunt3r** [comment] 2019-03-15 11:09
Can you explain this a bit more. I thought title is for representing the Title not for rearangement of some positions.

**Comment by johnknoop** [comment] 2019-04-04 18:22
I'm seeing this issue as well, for every case where the reference element is float: right or right-aligned using flex.

**Comment by FezVrasta** [comment] 2019-12-16 13:32
This seems to be fixed in v2
https://codepen.io/FezVrasta/pen/mdyOPxj

**Closed** 2019-12-18 19:34 UTC
Labels: # BUG, Fixed in v2, PRIORITY: low
