### ISSUE TITLE
Tooltip doesn't get hidden (not always, but often)

### ISSUE THREAD

**Issue by peda** [popperjs/popper.js#808] opened 2019-07-24 18:47 UTC
### CodePen demo

https://codepen.io/anon/pen/rXLNXP

### Steps to reproduce the problem

1.  open the CodePen
2.  move the mouse cursor over the red trigger element and what at least a second for the tooltip to show up
3.  move the mouse into the tooltip wait a moment and then move the mouse (fast) further to the right and of the tooltip
4. in approximately 1 on out of 5 cases the tooltip doesn't hide and stays there indefinitely

### What is the expected behavior?

The tooltip should hide when the trigger is set to "hover" and the mouse isn't hovering the trigger or the tooltip

### What went wrong?

The tooltip doesn't get hidden in some cases

**Comment by AlexanderSergan** [comment] 2019-08-02 08:46
### Gif of reproduced bug
@peda, thanks for creating the issue. I reproduced the problem and recorded it for better visualisation.
The bug is catched on at 5th try.
![tooltip](https://user-images.githubusercontent.com/6415224/62357006-e4911000-b51a-11e9-8583-fd00a2fc7345.gif)

**Comment by MBing** [comment] 2019-08-15 08:04
https://popper.js.org/popper-documentation.html#Popper.Defaults.removeOnDestroy

There's a typo that might cause this `removeOnDestroay` iso `removeOnDestroy`:
<img width="260" alt="Screenshot 2019-08-15 at 09 56 29" src="https://user-images.githubusercontent.com/2140223/63081081-fc1cbf80-bf42-11e9-914f-16fe936d80bc.png">

I tried to reproduce it before and it was as shown on the nice video. After the typo I couldn't reproduce it anymore.
Hope it helps!

**Comment by FezVrasta** [comment] 2019-08-15 08:46
@MBing even wit the typo fixed I can still reproduce it.

**Comment by robclancy** [comment] 2019-09-05 20:12
We have lots of tooltips and it completely randomly doesn't hide them sometimes. I gave up trying to find out why and just added a ticket to migrate to something else.

**Comment by FezVrasta** [comment] 2019-09-05 20:25
Thanks for the support @robclancy! I'm sure you will find a whole lot of open source maintainers willing to give your for free their time to fix your own problems with this attitude 👍

**Comment by robclancy** [comment] 2019-09-05 20:32
No worries. I don't plan to support a tooltip library that can't consistently hide a tooltip anyway :) And has open issues from over a year ago where things are tagged as "low difficulty". Oh and doesn't even provide CSS for arrows to the point we had to use view source to find something usable.

There are lots of people with a "good attitude" without this maintainer fixing their issues.

It's nice to see people still can't take it when their bugs make people not want to use their product. I already spent hours trying to find the issue because I knew even if I posted it you wouldn't try anyway. As shown by this issue.

**Comment by alessandro-newzoo** [comment] 2019-11-20 09:39
oh my God did you just thumb up your own comment? Hilarious.

**Comment by robclancy** [comment] 2019-11-20 16:21
@alessandro-newzoo ;)

**Comment by FezVrasta** [comment] 2019-11-22 10:31
Hi, I'm interrupting the development of the `tooltip.js` library to focus on the development of `@popperjs/core` (Popper.js v2).

Please consider switching to [Tippy.js](https://github.com/atomiks/tippyjs), which is a way better alternative to Tooltip.js and is well maintained. Tippy.js still uses Popper.js under the hood, so you will find all your favourite features.

I'll close this issue.

**Closed by FezVrasta** 2019-11-22 10:31 UTC
Labels: # BUG, TARGETS: Tooltip.js
